packages:
  - packages/*
  - packages/plugins/*
  - demos/*
  - templates/*
  - packages/blocks/playground
  - e2e/fixture
  - docs
  - slidev

catalog:
  "@arethetypeswrong/cli": ^0.18.2
  "@astrojs/check": ^0.9.8
  "@astrojs/cloudflare": ^13.1.8
  "@astrojs/node": ^10.0.4
  "@astrojs/react": ^5.0.3
  "@cloudflare/workers-types": ^4.20260405.1
  "@phosphor-icons/react": ^2.1.10
  "@tanstack/react-query": 5.96.2
  "@tanstack/react-router": 1.168.10
  "@tiptap/core": ^3.22.2
  "@tiptap/extension-character-count": ^3.22.2
  "@tiptap/extension-drag-handle": ^3.22.2
  "@tiptap/extension-drag-handle-react": ^3.22.2
  "@tiptap/extension-dropcursor": ^3.22.2
  "@tiptap/extension-focus": ^3.22.2
  "@tiptap/extension-image": ^3.22.2
  "@tiptap/extension-link": ^3.22.2
  "@tiptap/extension-node-range": ^3.22.2
  "@tiptap/extension-placeholder": ^3.22.2
  "@tiptap/extension-text-align": ^3.22.2
  "@tiptap/extension-typography": ^3.22.2
  "@tiptap/extension-underline": ^3.22.2
  "@tiptap/pm": ^3.22.2
  "@tiptap/react": ^3.22.2
  "@tiptap/starter-kit": ^3.22.2
  "@tiptap/suggestion": ^3.22.2
  "@types/node": 24.10.13
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  astro: ^6.1.4
  better-sqlite3: ^11.10.0
  publint: 0.3.18
  react: 19.2.4
  react-dom: 19.2.4
  tsdown: 0.21.7
  typescript: ^5.9.3
  vitest: ^4.1.3
  wrangler: ^4.81.0
